### PR TITLE
feat(api): refactor parse and add setup.py

### LINKED ISSUE #20: Make sure hearingType is included in the scraped data

### LINKED ISSUE #21: Include hearing type as apart of the unique identifier for each case event

### LINKED ISSUE #24: Refactor parse
Think we can include some data models here and parse entire `.htm` pages into these classes.  Maybe need some wonky splitting on these pages but will see what I can do

### PR DESCRIPTION
**Pull request by jayceslesar**
Quick refactor for the `calendar_parse.py` and adds a `setup.py` so we can just `pip install .` when inside the repo, instead of `pip install -r requirements.txt`. 

- [x] add `setup.py`
- [x] refactor `calendar_parse.py`
- [ ] integrate with tests

Closes #20 
Closes #21 
Closes #24

### CODE REVIEW

**Comment by jayceslesar** [comment]
Still a few things to do here (mostly test related)

But also curious why the other code is in a different repository?

I guess I need to dig in a little more and look at how the database is all set up.

**Comment by iamyume** [comment]
I'm trying to run thru the setup from a new clean virtual environment and can't get past the `pip install .` phase. I get the following error output
```
(env) ➜  courtbot-vt git:(feature/refactor-improve-parse) ✗ pip install .
Processing /home/yume/coding-projects/code-for-btv/courtbot-vt
Requirement already satisfied: bs4==0.0.1 in ./env/lib/python3.8/site-packages (from courtbot-vt==0.1.dev72+ge86f67e.d20220323)
Requirement already satisfied: importlib-metadata==3.7.3 in ./env/lib/python3.8/site-packages (from courtbot-vt==0.1.dev72+ge86f67e.d20220323)
Requirement already satisfied: iniconfig==1.1.1 in ./env/lib/python3.8/site-packages (from courtbot-vt==0.1.dev72+ge86f67e.d20220323)
Requirement already satisfied: packaging==20.9 in ./env/lib/python3.8/site-packages (from courtbot-vt==0.1.dev72+ge86f67e.d20220323)
Collecting pandas==1.2.1 (from courtbot-vt==0.1.dev72+ge86f67e.d20220323)
  Using cached https://files.pythonhosted.org/packages/ac/00/b52d3ae41ce14c4adef5d2a6952c46ed733ff9d1b33fc1aa423db0a6c1cd/pandas-1.2.1-cp38-cp38-manylinux1_x86_64.whl
Collecting pymongo==3.12.0 (from courtbot-vt==0.1.dev72+ge86f67e.d20220323)
  Using cached https://files.pythonhosted.org/packages/ba/3a/ea837307e36f8d182341b2cb21196b777f19681473040188cf9299721623/pymongo-3.12.0-cp38-cp38-manylinux1_x86_64.whl
Collecting pytest==6.2.2 (from courtbot-vt==0.1.dev72+ge86f67e.d20220323)
  Using cached https://files.pythonhosted.org/packages/a1/cf/7f67585bd2fc0359ec482cf3c430bce3ef6d3f40bc468137225a733e3069/pytest-6.2.2-py3-none-any.whl
Collecting python-dotenv==0.19.1 (from courtbot-vt==0.1.dev72+ge86f67e.d20220323)
  Using cached https://files.pythonhosted.org/packages/af/85/7433188f5811856dabe0c7bccc832a23c2fd49b48fc57373d9c10747a1ea/python_dotenv-0.19.1-py2.py3-none-any.whl
Requirement already satisfied: pytz==2020.4 in ./env/lib/python3.8/site-packages (from courtbot-vt==0.1.dev72+ge86f67e.d20220323)
Collecting requests==2.24.0 (from courtbot-vt==0.1.dev72+ge86f67e.d20220323)
  Using cached https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl
Requirement already satisfied: beautifulsoup4 in ./env/lib/python3.8/site-packages (from bs4==0.0.1->courtbot-vt==0.1.dev72+ge86f67e.d20220323)
Requirement already satisfied: zipp>=0.5 in ./env/lib/python3.8/site-packages (from importlib-metadata==3.7.3->courtbot-vt==0.1.dev72+ge86f67e.d20220323)
Requirement already satisfied: pyparsing>=2.0.2 in ./env/lib/python3.8/site-packages (from packaging==20.9->courtbot-vt==0.1.dev72+ge86f67e.d20220323)
Collecting numpy>=1.16.5 (from pandas==1.2.1->courtbot-vt==0.1.dev72+ge86f67e.d20220323)
  Using cached https://files.pythonhosted.org/packages/64/4a/b008d1f8a7b9f5206ecf70a53f84e654707e7616a771d84c05151a4713e9/numpy-1.22.3.zip
Collecting python-dateutil>=2.7.3 (from pandas==1.2.1->courtbot-vt==0.1.dev72+ge86f67e.d20220323)
  Using cached https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl
Collecting py>=1.8.2 (from pytest==6.2.2->courtbot-vt==0.1.dev72+ge86f67e.d20220323)
  Using cached https://files.pythonhosted.org/packages/f6/f0/10642828a8dfb741e5f3fbaac830550a518a775c7fff6f04a007259b0548/py-1.11.0-py2.py3-none-any.whl
Collecting attrs>=19.2.0 (from pytest==6.2.2->courtbot-vt==0.1.dev72+ge86f67e.d20220323)
  Using cached https://files.pythonhosted.org/packages/be/be/7abce643bfdf8ca01c48afa2ddf8308c2308b0c3b239a44e57d020afa0ef/attrs-21.4.0-py2.py3-none-any.whl
Collecting pluggy<1.0.0a1,>=0.12 (from pytest==6.2.2->courtbot-vt==0.1.dev72+ge86f67e.d20220323)
  Using cached https://files.pythonhosted.org/packages/a0/28/85c7aa31b80d150b772fbe4a229487bc6644da9ccb7e427dd8cc60cb8a62/pluggy-0.13.1-py2.py3-none-any.whl
Collecting toml (from pytest==6.2.2->courtbot-vt==0.1.dev72+ge86f67e.d20220323)
  Using cached https://files.pythonhosted.org/packages/44/6f/7120676b6d73228c96e17f1f794d8ab046fc910d781c8d151120c3f1569e/toml-0.10.2-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests==2.24.0->courtbot-vt==0.1.dev72+ge86f67e.d20220323)
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests==2.24.0->courtbot-vt==0.1.dev72+ge86f67e.d20220323)
  Using cached https://files.pythonhosted.org/packages/37/45/946c02767aabb873146011e665728b680884cd8fe70dde973c640e45b775/certifi-2021.10.8-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests==2.24.0->courtbot-vt==0.1.dev72+ge86f67e.d20220323)
  Using cached https://files.pythonhosted.org/packages/56/aa/4ef5aa67a9a62505db124a5cb5262332d1d4153462eb8fd89c9fa41e5d92/urllib3-1.25.11-py2.py3-none-any.whl
Collecting chardet<4,>=3.0.2 (from requests==2.24.0->courtbot-vt==0.1.dev72+ge86f67e.d20220323)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Requirement already satisfied: soupsieve>1.2 in ./env/lib/python3.8/site-packages (from beautifulsoup4->bs4==0.0.1->courtbot-vt==0.1.dev72+ge86f67e.d20220323)
Collecting six>=1.5 (from python-dateutil>=2.7.3->pandas==1.2.1->courtbot-vt==0.1.dev72+ge86f67e.d20220323)
  Using cached https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Building wheels for collected packages: courtbot-vt, numpy
  Running setup.py bdist_wheel for courtbot-vt ... error
  Complete output from command /home/yume/coding-projects/code-for-btv/courtbot-vt/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-yjr9ev7z-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp2jri4zi_pip-wheel- --python-tag cp38:
  /tmp/pip-yjr9ev7z-build/.eggs/setuptools_scm-6.4.2-py3.8.egg/setuptools_scm/integration.py:17: RuntimeWarning:
  ERROR: setuptools==39.0.1 is used in combination with setuptools_scm>=6.x

  Your build configuration is incomplete and previously worked by accident!


  This happens as setuptools is unable to replace itself when a activated build dependency
  requires a more recent setuptools version
  (it does not respect "setuptools>X" in setup_requires).


  setuptools>=31 is required for setup.cfg metadata support
  setuptools>=42 is required for pyproject.toml configuration support

  Suggested workarounds if applicable:
   - preinstalling build dependencies like setuptools_scm before running setup.py
   - installing setuptools_scm using the system package manager to ensure consistency
   - migrating from the deprecated setup_requires mechanism to pep517/518
     and using a pyproject.toml to declare build dependencies
     which are reliably pre-installed before running the build tools

    warnings.warn(
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for courtbot-vt
  Running setup.py clean for courtbot-vt
  Running setup.py bdist_wheel for numpy ... error
  Complete output from command /home/yume/coding-projects/code-for-btv/courtbot-vt/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-oslxvp3r/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpvs4eze6ipip-wheel- --python-tag cp38:
  Running from numpy source directory.
  Cythonizing sources
  Processing numpy/random/_bounded_integers.pxd.in
  Processing numpy/random/_pcg64.pyx
  Traceback (most recent call last):
    File "/tmp/pip-build-oslxvp3r/numpy/tools/cythonize.py", line 53, in process_pyx
      import Cython
  ModuleNotFoundError: No module named 'Cython'

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/tmp/pip-build-oslxvp3r/numpy/tools/cythonize.py", line 234, in <module>
      main()
    File "/tmp/pip-build-oslxvp3r/numpy/tools/cythonize.py", line 230, in main
      find_process_files(root_dir)
    File "/tmp/pip-build-oslxvp3r/numpy/tools/cythonize.py", line 221, in find_process_files
      process(root_dir, fromfile, tofile, function, hash_db)
    File "/tmp/pip-build-oslxvp3r/numpy/tools/cythonize.py", line 187, in process
      processor_function(fromfile, tofile)
    File "/tmp/pip-build-oslxvp3r/numpy/tools/cythonize.py", line 60, in process_pyx
      raise OSError(msg) from e
  OSError: Cython needs to be installed in Python as a module
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-oslxvp3r/numpy/setup.py", line 461, in <module>
      setup_package()
    File "/tmp/pip-build-oslxvp3r/numpy/setup.py", line 443, in setup_package
      generate_cython()
    File "/tmp/pip-build-oslxvp3r/numpy/setup.py", line 248, in generate_cython
      raise RuntimeError("Running cythonize failed!")
  RuntimeError: Running cythonize failed!

  ----------------------------------------
  Failed building wheel for numpy
  Running setup.py clean for numpy
  Complete output from command /home/yume/coding-projects/code-for-btv/courtbot-vt/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-oslxvp3r/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Running from numpy source directory.

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).


  ----------------------------------------
  Failed cleaning build dir for numpy
Failed to build courtbot-vt numpy
Installing collected packages: numpy, six, python-dateutil, pandas, pymongo, py, attrs, pluggy, toml, pytest, python-dotenv, idna, certifi, urllib3, chardet, requests, courtbot-vt
  Running setup.py install for numpy ... error
    Complete output from command /home/yume/coding-projects/code-for-btv/courtbot-vt/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-oslxvp3r/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pxamd0wy-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/yume/coding-projects/code-for-btv/courtbot-vt/env/include/site/python3.8/numpy:
    Running from numpy source directory.

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install numpy`   (last NumPy release on PyPi)


    Cythonizing sources
    numpy/random/_bounded_integers.pxd.in has not changed
    Processing numpy/random/_pcg64.pyx
    Traceback (most recent call last):
      File "/tmp/pip-build-oslxvp3r/numpy/tools/cythonize.py", line 53, in process_pyx
        import Cython
    ModuleNotFoundError: No module named 'Cython'

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/tmp/pip-build-oslxvp3r/numpy/tools/cythonize.py", line 234, in <module>
        main()
      File "/tmp/pip-build-oslxvp3r/numpy/tools/cythonize.py", line 230, in main
        find_process_files(root_dir)
      File "/tmp/pip-build-oslxvp3r/numpy/tools/cythonize.py", line 221, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/pip-build-oslxvp3r/numpy/tools/cythonize.py", line 187, in process
        processor_function(fromfile, tofile)
      File "/tmp/pip-build-oslxvp3r/numpy/tools/cythonize.py", line 60, in process_pyx
        raise OSError(msg) from e
    OSError: Cython needs to be installed in Python as a module
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-oslxvp3r/numpy/setup.py", line 461, in <module>
        setup_package()
      File "/tmp/pip-build-oslxvp3r/numpy/setup.py", line 443, in setup_package
        generate_cython()
      File "/tmp/pip-build-oslxvp3r/numpy/setup.py", line 248, in generate_cython
        raise RuntimeError("Running cythonize failed!")
    RuntimeError: Running cythonize failed!

    ----------------------------------------
Command "/home/yume/coding-projects/code-for-btv/courtbot-vt/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-oslxvp3r/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pxamd0wy-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/yume/coding-projects/code-for-btv/courtbot-vt/env/include/site/python3.8/numpy" failed with error code 1 in /tmp/pip-build-oslxvp3r/numpy/
```

Is this something wrong on my end?

**Comment by jayceslesar** [comment]
@iamyume if you `pip3 install --upgrade pip setuptools wheel` and retry it should fix things, looks like old version of all 3

**Comment by iamyume** [comment]
yes that did the trick thanks. Will be reviewing the PR this week. Thanks for all the work you've put in.

**Comment by jayceslesar** [comment]
@iamyume for sure, fun to code stuff that helps people! Couldn't make it tonight (even though I was signed up) due to bad cold - need to sleep instead of stare at screens haha

**Comment by iamyume** [comment]
Ok starting running the script and got an error pretty quickly. I can dive into things a little bit later, but probably would be best at least to wrap each event parsing in a try statement so an error won't crash the rest of the run
```
(env) ➜  courtbot-vt git:(feature/refactor-improve-parse) ✗ python3 main.py
INFO:root:Parsing all court calendars found at https://www.vermontjudiciary.org/court-calendars
INFO:root:Beginning to collect court calendar urls.
INFO:root:Finished collecting court calendar urls
INFO:root:Parsing URL https://www.vermontjudiciary.org/courts/court-calendars/ans_cal.htm. addison county, civil division.
INFO:root:Parsing URL https://www.vermontjudiciary.org/courts/court-calendars/and_cal.htm. addison county, criminal division.
Traceback (most recent call last):
  File "main.py", line 54, in <module>
    main()
  File "main.py", line 37, in main
    all_court_events = parser.parse_all(CALENDAR_ROOT_URL)
  File "/home/yume/coding-projects/code-for-btv/courtbot-vt/src/parse/calendar_parse.py", line 322, in parse_all
    all_court_events += parse_calendar(court_url)
  File "/home/yume/coding-projects/code-for-btv/courtbot-vt/src/parse/calendar_parse.py", line 260, in parse_calendar
    event_blocks += parse_day(day_text, date)
  File "/home/yume/coding-projects/code-for-btv/courtbot-vt/src/parse/calendar_parse.py", line 177, in parse_day
    event_blocks += parse_courtroom_from_day(split, date)
  File "/home/yume/coding-projects/code-for-btv/courtbot-vt/src/parse/calendar_parse.py", line 159, in parse_courtroom_from_day
    event_blocks.append(parse_event_block(case_text, date))
  File "/home/yume/coding-projects/code-for-btv/courtbot-vt/src/parse/calendar_parse.py", line 127, in parse_event_block
    full_date = VT_TIMEZONE.localize(datetime(date.year, date.month, date.day, hour, minute))
ValueError: hour must be in 0..23
```

**Comment by jayceslesar** [comment]
> Ok starting running the script and got an error pretty quickly. I can dive into things a little bit later, but probably would be best at least to wrap each event parsing in a try statement so an error won't crash the rest of the run
> 
> ```
> (env) ➜  courtbot-vt git:(feature/refactor-improve-parse) ✗ python3 main.py
> INFO:root:Parsing all court calendars found at https://www.vermontjudiciary.org/court-calendars
> INFO:root:Beginning to collect court calendar urls.
> INFO:root:Finished collecting court calendar urls
> INFO:root:Parsing URL https://www.vermontjudiciary.org/courts/court-calendars/ans_cal.htm. addison county, civil division.
> INFO:root:Parsing URL https://www.vermontjudiciary.org/courts/court-calendars/and_cal.htm. addison county, criminal division.
> Traceback (most recent call last):
>   File "main.py", line 54, in <module>
>     main()
>   File "main.py", line 37, in main
>     all_court_events = parser.parse_all(CALENDAR_ROOT_URL)
>   File "/home/yume/coding-projects/code-for-btv/courtbot-vt/src/parse/calendar_parse.py", line 322, in parse_all
>     all_court_events += parse_calendar(court_url)
>   File "/home/yume/coding-projects/code-for-btv/courtbot-vt/src/parse/calendar_parse.py", line 260, in parse_calendar
>     event_blocks += parse_day(day_text, date)
>   File "/home/yume/coding-projects/code-for-btv/courtbot-vt/src/parse/calendar_parse.py", line 177, in parse_day
>     event_blocks += parse_courtroom_from_day(split, date)
>   File "/home/yume/coding-projects/code-for-btv/courtbot-vt/src/parse/calendar_parse.py", line 159, in parse_courtroom_from_day
>     event_blocks.append(parse_event_block(case_text, date))
>   File "/home/yume/coding-projects/code-for-btv/courtbot-vt/src/parse/calendar_parse.py", line 127, in parse_event_block
>     full_date = VT_TIMEZONE.localize(datetime(date.year, date.month, date.day, hour, minute))
> ValueError: hour must be in 0..23
> ```

looks like its converting the 12 in 12:30 to 24....looking

**Comment by jayceslesar** [comment]
@iamyume just fixed the bad hour, still fails on 2 pages I think? One because environmental doesnt have a county and the other is somewhere in a slack thread

**Pull request closed without merging**
